module.exports = {
    SUCCESS_CODE: 200,
    CREATED: 201,
    REQ_DATING_ERROR_CODE: 204,
    ERROR_CODE: 400,
    INVALID_CODE: 401,
    FORBIDDEN_CODE: 403,
    INACTIVATE: 406,
    NOT_FOUND: 404,
    CONFLICT: 409,
    SERVER_ERROR: 500,
    REQUEST_NOT_FOUND: 'Request not found',
    EMAIL_ALREADY_REGISTERED: 'Email already registered.',
    INVAILID_DATA: 'Registration form data is not correct.',
    USER_SAVE_SUCCESS: 'Registration completed successfully',
    USER_DELETED_SUCCESS: 'User deleted successfully',
    USER_NOT_AUTHORIZED: 'You are not Authorized',
    USER_RETRIEVE_SUCCESS: 'User retrieve successfully',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    USER_LOGIN_SUCCESS: 'User Login successfully',
    USER_DATA_UPDATE_SUCCESS: 'User update successfully',
    USER_VERIFICATION_SUCCESS: 'User verified',
    USER_EMAIL_PASSWORD: "You have entered an invalid email or password",
    EMAIL_VERIFIED: 'Email successfully verified.',
    INVALID_TOKEN: "Invalid Token",
    USER_EMAIL_NOT_REGISTERED: "This email is not registered.",
    SENT_FORGOT_EMAIL: "Email sent successfully.",
    USER_RESET_PASSWORD: 'Reset password token expires! Regenerate token to set password',
    USER_OLD_PASSWORD: 'User old password did not matched',
    PASSWORD_RESET: "Password reset successfully",
    DATA_DELETED_SUCCESS: 'Data deleted successfully',
    SAVE_SUCCESS: 'Requested record created successfully',
    UPDATED_SUCCESS: 'Requested record updated successfully',
    DELETED_SUCCESS: 'Requested record deleted successfully',
    RETRIEVE_SUCCESS: 'Record(s) retrieve successfully',
    VERIFIED_SUCCESS: 'Request successfully verified.',

}